# Generated by Django 5.0.3 on 2024-03-13 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('customer_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('employee_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('initial_password', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('message_of', models.CharField(choices=[('WORK', 'WORK'), ('CUSTOMER', 'CUSTOMER'), ('TODAY_WORK', 'TODAY_WORK')], default='', max_length=30)),
                ('once_passed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_serial', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purifier.category')),
                ('services', models.ManyToManyField(blank=True, to='purifier.service')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_purchase_date', models.DateField(auto_now_add=True)),
                ('product_service_history', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purifier.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purifier.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='installed_product',
            field=models.ManyToManyField(blank=True, to='purifier.product'),
        ),
        migrations.CreateModel(
            name='Servicer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purifier.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service_work_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('comment_section', models.TextField(blank=True, null=True)),
                ('service_date', models.DateField()),
                ('remark_section', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purifier.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purifier.product')),
                ('service_name', models.ManyToManyField(to='purifier.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAssign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notification', models.CharField(blank=True, max_length=500)),
                ('servicer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purifier.servicer')),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='purifier.servicework')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('test_name', models.CharField(max_length=150)),
                ('ph_value', models.CharField(max_length=30)),
                ('tds_value', models.CharField(max_length=30)),
                ('iron_value', models.CharField(max_length=30)),
                ('hardness_value', models.CharField(max_length=30)),
                ('turbuet_value', models.CharField(max_length=30)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purifier.customer')),
            ],
        ),
    ]
