# Generated by Django 5.0.3 on 2024-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='initial_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
