# Generated by Django 5.0.3 on 2024-03-22 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0004_remove_serviceassign_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('message_of', models.CharField(choices=[('SERVICE_WORK_COMPLETED', 'SERVICE_WORK_COMPLETED'), ('NEW_CUSTOMER', 'NEW_CUSTOMER'), ('TODAY_WORK', 'TODAY_WORK')], default='', max_length=30)),
                ('once_passed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('message_of', models.CharField(choices=[('SERVICE_COMPLETED', 'SERVICE_COMPLETED'), ('TOMORROW_SERVICES', 'TOMORROW_SERVICES'), ('TODAY_SERVICES', 'TODAY_SERVICES')], default='', max_length=30)),
                ('once_passed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purifier.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('message_of', models.CharField(choices=[('SERVICE_ASSIGNED', 'SERVICE_ASSIGNED'), ('TODAY_WORKS', 'TODAY_WORKS')], default='', max_length=30)),
                ('once_passed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purifier.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
