# Generated by Django 5.0.3 on 2024-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0005_adminnotification_customernotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_serial',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
