# Generated by Django 5.0.3 on 2024-03-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0006_alter_product_product_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernotification',
            name='message_of',
            field=models.CharField(choices=[('SERVICE_COMPLETED', 'SERVICE_COMPLETED'), ('SERVICE_NEW', 'SERVICE_NEW'), ('TOMORROW_SERVICES', 'TOMORROW_SERVICES'), ('TODAY_SERVICES', 'TODAY_SERVICES')], default='', max_length=30),
        ),
    ]
