# Generated by Django 5.0.3 on 2024-03-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0007_alter_customernotification_message_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicework',
            name='servicer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purifier.servicer'),
        ),
    ]
