# Generated by Django 5.0.3 on 2024-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0008_servicework_servicer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
